import { StyleSheet } from "react-native";

import { colors } from "./colors";

export const qrScannerStyles = StyleSheet.create({
  camera: { flex: 1, backgroundColor: "#000" },
  cameraFill: {
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  overlay: { flex: 1, justifyContent: "space-between", padding: 24 },
  overlayTop: { alignItems: "center", flexDirection: "row", gap: 14 },
  close: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.92)",
    borderRadius: 22,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  closeText: {
    color: colors.textDark,
    fontSize: 28,
    fontWeight: "300",
    lineHeight: 30,
  },
  scanTitle: { color: colors.white, fontSize: 18, fontWeight: "800" },
  scanCopy: { color: "#E2E8F0", fontSize: 13, marginTop: 3 },
  frame: {
    alignSelf: "center",
    borderColor: colors.white,
    borderRadius: 22,
    borderWidth: 2,
    height: 240,
    width: 240,
  },
  hint: {
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.55)",
    borderRadius: 18,
    color: colors.white,
    fontSize: 13,
    marginBottom: 20,
    overflow: "hidden",
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  state: {
    alignItems: "center",
    backgroundColor: colors.background,
    flex: 1,
    justifyContent: "center",
    padding: 30,
  },
  stateIcon: {
    alignItems: "center",
    backgroundColor: colors.surfaceMuted,
    borderRadius: 35,
    height: 70,
    justifyContent: "center",
    width: 70,
  },
  stateIconText: { color: colors.primary, fontSize: 36 },
  stateTitle: {
    color: colors.textDark,
    fontSize: 22,
    fontWeight: "800",
    marginTop: 20,
    textAlign: "center",
  },
  stateCopy: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
    textAlign: "center",
  },
  permissionButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    marginTop: 26,
    paddingHorizontal: 22,
    paddingVertical: 15,
  },
  permissionText: { color: colors.white, fontSize: 15, fontWeight: "800" },
  cancel: { marginTop: 20, padding: 10 },
  cancelText: { color: colors.primary, fontSize: 14, fontWeight: "800" },
});
